name: geo_monitor
description: Geo Monitor Version 1.1
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

#  location: ^5.0.0-dev.8
  localstorage: ^4.0.0+1
  cupertino_icons: ^1.0.5
  go_router: ^6.0.1
  firebase_auth: ^4.2.5
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  permission_handler: ^10.2.0
  unicorndial: ^1.1.5
  path_provider: ^2.0.11
  material_design_icons_flutter: ^6.0.7096
  flutter_google_places: ^0.3.0
  intl: ^0.17.0
  http: ^0.13.5
  google_maps_flutter: ^2.2.3
  google_maps_webservice: ^0.0.19
  autocomplete_textfield: ^2.0.1
  location: ^4.4.0
  path: ^1.8.2
  cached_network_image: ^3.2.3
  flutter_dotenv: ^5.0.2
  page_transition: ^2.0.9
  responsive_builder: ^0.5.0+1
  google_fonts: ^4.0.1
  image: ^4.0.12
  video_thumbnail: ^0.5.3
  android_intent: ^2.0.2
  flutter_credit_card: ^3.0.5
  uuid: ^3.0.7
  geocoding:
  chewie: ^1.4.0
  video_player: ^2.5.1
  camera: ^0.10.2+1
  maps_toolkit: ^2.0.1
  focused_menu: ^1.0.5
  universal_platform: ^1.0.0+1
  flutter_staggered_grid_view: ^0.6.2
  transparent_image: ^2.0.0
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^13.0.0
  image_picker:
  animations:
  get:
  crypto:
  hive: ^2.2.3
  fluttertoast: ^8.1.2
  georange: ^1.0.0
  geofence_service: ^3.5.0
  firebase_ui_auth: ^1.1.9
  firebase_dynamic_links: ^5.0.11
  flex_color_scheme: ^6.1.2
  flutter_riverpod: ^2.1.3
  native_device_orientation: ^1.1.4
  google_maps_utils: ^1.5.0+0
  google_maps_cluster_manager: ^3.0.0+1
  stream_channel: ^2.1.1
  badges: ^3.0.2
  map_launcher: ^2.4.0
  connectivity_plus: ^3.0.2
  dots_indicator: ^2.1.0
  flutter_libphonenumber: ^1.3.0
  firebase_crashlytics: ^3.0.11
  pin_code_fields: ^7.4.0
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.3.0
  record: ^4.4.4
  mic_stream: ^0.6.4
  audio_waveforms: ^1.0.1
  just_audio: ^0.9.31
  restart_app: ^1.1.2
  flutter_rating_bar: ^4.0.1
  get_storage: ^2.0.3
  isolate_handler: ^1.0.2
  flutter_email_sender: ^5.2.0
  flutter_chat_ui: ^1.6.6
  file_picker: ^5.2.5
  open_filex: ^4.3.2
  flutter_chat_types: ^3.6.0
  mime: ^1.0.4
  url_launcher: ^6.1.8
  archive: ^3.3.6
  lat_lng_to_timezone: ^0.2.0
  photo_view: ^0.14.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner:
  hive_generator:


flutter:

  uses-material-design: true

  assets:
    - assets/intro/
    - assets/mapicons/
    - assets/
    - .env
