name: aftarobot_dart_functions
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none
environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies:
  args: ^2.3.0
  shelf: ^1.2.0
  shelf_router: ^1.1.1
  functions_framework: ^0.4.1
  json_annotation: ^4.1.0
  aftarobotlibrary4:
    path: ../../DANCER_REPO/aftarobotlibrary4/aftarobotlibrary4

dev_dependencies:
  http: ^0.13.3
  lints: ^1.0.1
  test_process: ^2.0.2
  test: ^1.17.12
